<template>
  <div id="savebank" style="color: #ffffff; padding: 20px;">
    <h1>风灵作成存档银行</h1>
    <br />
    <div id="saves">
      <template v-for="(category, catIndex) in categories" :key="catIndex">
        <div 
          class="saves category-header" 
          :style="category.styles"
          @click="toggleCategory(catIndex)"
        >
          <span>{{ category.name }}<span v-if="displays[catIndex]"> ▼</span><span v-else> ▶</span></span>
        </div>
        <br /><br />
        <div v-show="displays[catIndex]">
          <template v-for="(save, saveIndex) in category.saves" :key="saveIndex">
            <div class="saves" v-if="save.name">
              <span style="font-size: 20px">{{ save.name }}</span><br />
              <span style="font-size: 16px; font-style: italic">{{ save.desc }}</span><br />
              <span style="font-size: 12px">由{{ save.author }}上传</span><br />
              <button class="btn" @click="copySave(catIndex, saveIndex)">粘贴至剪贴板</button>
              <button class="btn" @click="downloadSave(catIndex, saveIndex)">以.txt形式保存</button>
            </div>
            <br /><br />
          </template>
        </div>
      </template>
    </div>
    <br />
    <button class="btn" @click="goBack">返回</button>
  </div>
</template>

<script setup>
import { defineProps, defineEmits, reactive, ref } from 'vue'

const props = defineProps({
  player: Object,
  v: Object
})

const emit = defineEmits(['switchPage'])

const displays = reactive(Array(10).fill(false))

function toggleCategory(index) {
  displays[index] = !displays[index]
}

function goBack() {
  emit('switchPage', 'p0_3')
}

function copySave(catIndex, saveIndex) {
  const save = categories[catIndex].saves[saveIndex]
  navigator.clipboard.writeText(save.data).then(() => {
    alert('存档已复制到剪贴板！')
  }).catch(() => {
    alert('复制失败，请手动复制')
  })
}

function downloadSave(catIndex, saveIndex) {
  const save = categories[catIndex].saves[saveIndex]
  const str = save.data
  const file = new Blob([str], { type: 'text/plain' })
  const url = window.URL || window.webkitURL
  const a = document.createElement('a')
  a.href = url.createObjectURL(file)
  a.download = save.name + '.txt'
  a.click()
}

const categories = [
  {
    name: '风灵阶段',
    styles: 'background-color: #ffffff; color: #000000; font-size: 24px',
    saves: [
      {
        name: '开局档',
        desc: '游戏最开始的样子',
        data: 'eyJlbmVyZ3kiOiIyIiwiZW5lcmd5dHRsIjoiMiIsIndzY2IwMSI6IjAiLCJ3c2NiMDIiOiIwIiwid3NjYjAzIjoiMCIsIndzY2IwNCI6IjAiLCJ3c2NiMDUiOiIwIiwid3NjYjA2IjoiMCIsIndzY2IwNyI6IjAiLCJ3c2NiMDgiOiIwIiwid3NjYjA5IjoiMCIsIndzY2IxMCI6IjAiLCJ3c2NiMTEiOiIwIiwid3NjYjEyIjoiMCIsIndzY2IxMyI6IjAiLCJ3c2NiMTQiOiIwIiwid3NjYjE1IjoiMCIsIndzY2IxNiI6IjAiLCJ3c2NiMTciOiIwIiwid3NjYjE4IjoiMCIsIndzY2IxOSI6IjAiLCJ3c2NiMjAiOiIwIiwid3NjYjIxIjoiMCIsIndzY2IyMiI6IjAiLCJ3c2NiMjMiOiIwIiwid3NjYjI0IjoiMCIsIndzY2IyNSI6IjAiLCJ3c2NiMjYiOiIwIiwid3NjYjI3IjoiMCIsIndzY2IyOCI6IjAiLCJ3c2NiMjkiOiIwIiwid3NjYjMwIjoiMCIsIndzY2IzMSI6IjAiLCJ3c2NiMzIiOiIwIiwid3NjYjMzIjoiMCIsIndzY2IzNCI6IjAiLCJ3c2NiMzUiOiIwIiwid3NjYjM2IjoiMCIsIndzY2IzNyI6IjAiLCJ3c2NiMzgiOiIwIiwid3NjYjM5IjoiMCIsIndzY2I0MCI6IjAiLCJ3c2NhMDEiOiIwIiwid3NjYTAyIjoiMCIsIndzY2EwMyI6IjAiLCJ3c2NhMDQiOiIwIiwid3NjYTA1IjoiMCIsIndzY2EwNiI6IjAiLCJ3c2NhMDciOiIwIiwid3NjYTA4IjoiMCIsIndzY2EwOSI6IjAiLCJ3c2NhMTAiOiIwIiwid3NjYTExIjoiMCIsIndzY2ExMiI6IjAiLCJ3c2NhMTMiOiIwIiwid3NjYTE0IjoiMCIsIndzY2ExNSI6IjAiLCJ3c2NhMTYiOiIwIiwid3NjYTE3IjoiMCIsIndzY2ExOCI6IjAiLCJ3c2NhMTkiOiIwIiwid3NjYTIwIjoiMCIsIndzY2EyMSI6IjAiLCJ3c2NhMjIiOiIwIiwid3NjYTIzIjoiMCIsIndzY2EyNCI6IjAiLCJ3c2NhMjUiOiIwIiwid3NjYTI2IjoiMCIsIndzY2EyNyI6IjAiLCJ3c2NhMjgiOiIwIiwid3NjYTI5IjoiMCIsIndzY2EzMCI6IjAiLCJ3c2NhMzEiOiIwIiwid3NjYTMyIjoiMCIsIndzY2EzMyI6IjAiLCJ3c2NhMzQiOiIwIiwid3NjYTM1IjoiMCIsIndzY2EzNiI6IjAiLCJ3c2NhMzciOiIwIiwid3NjYTM4IjoiMCIsIndzY2EzOSI6IjAiLCJ3c2NhNDAiOiIwIiwidGllcjAxIjoiMCIsInRpZXIwMiI6IjAiLCJ0aWVyMDMiOiIwIiwidGllcjA0IjoiMCIsInRpZXIwMWNvbmYiOmZhbHNlLCJ0aWVyMDJjb25mIjpmYWxzZSwidGllcjAzY29uZiI6ZmFsc2UsInRpZXIwNGNvbmYiOmZhbHNlLCJhdXRvYnV5dGllcjAxIjpmYWxzZSwiYXV0b2J1eXRpZXIwMiI6ZmFsc2UsImF1dG9idXl0aWVyMDMiOmZhbHNlLCJhdXRvYnV5dGllcjA0IjpmYWxzZSwidXBnZDAxIjoiMCIsInVwZ2QwMiI6IjAiLCJ1cGdkMDMiOiIwIiwidXBnZDA0IjoiMCIsImF1dG9idXl1cGdkMDEiOmZhbHNlLCJhdXRvYnV5dXBnZDAyIjpmYWxzZSwiYXV0b2J1eXVwZ2QwMyI6ZmFsc2UsImF1dG9idXl1cGdkMDQiOmZhbHNlLCJoYXNVbmxvY2tlZFBMMSI6ZmFsc2UsIlBMMWVuZXJneSI6IjEiLCJQTDFwdHMiOiIwIiwiUEwxcHRzdG90YWwiOiIwIiwiaGFzVW5sb2NrZWRQTDIiOmZhbHNlLCJQTDJlbmVyZ3kiOiIxIiwiUEwycHRzIjoiMCIsIlBMMnB0c3RvdGFsIjoiMCIsImhhc1VubG9ja2VkUEwzIjpmYWxzZSwiUEwzZW5lcmd5IjoiMSIsIlBMM3B0cyI6IjAiLCJQTDNwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMNCI6ZmFsc2UsIlBMM2VuZXJneSI6IjEiLCJQTDRwdHMiOiIwIiwiUEw0cHRzdG90YWwiOiIwIiwiaGFzVW5sb2NrZWRQTDUiOmZhbHNlLCJQTDVlbmVyZ3kiOiIxIiwiUEw1cHRzIjoiMCIsIlBMNXB0c3RvdGFsIjoiMCIsImluY2hhIjowLCJjaGFjb20wMSI6IjAiLCJjaGFjb20wMiI6IjAiLCJjaGFjb20wMyI6IjAiLCJjaGFjb20wNCI6IjAiLCJjaGFjb20wNSI6IjAiLCJjaGFjb20wNiI6IjAiLCJjaGFjb20wNyI6IjAiLCJjaGFjb20wOCI6IjAiLCJjaGFjb20wOSI6IjAiLCJjaGFjb20xMCI6IjAiLCJjaGFjb20xMSI6IjAiLCJjaGFjb20xMiI6IjAiLCJjaGFjb20xMyI6IjAiLCJjaGFjb20xNCI6IjAiLCJjaGFjb20xNSI6IjAiLCJjaGFjb20xNiI6IjAiLCJjaGFjb20xNyI6IjAiLCJjaGFjb20xOCI6IjAiLCJjaGFjb20xOSI6IjAiLCJjaGFjb20yMCI6IjAiLCJjaGFjb20yMSI6IjAiLCJjaGFjb20yMiI6IjAiLCJjaGFjb20yMyI6IjAiLCJjaGFjb20yNCI6IjAiLCJoYXNVbmxvY2tlZENoYSI6ZmFsc2UsImFjaGV2ZSI6W10sImF1dG9Db25maXJtIjpmYWxzZSwibWF4QWxsIjpmYWxzZSwidGltZSI6MCwibGFzdFRpbWUiOjAsInZlcnNpb24iOiI2LjAuMCJ9',
        author: '6左爷6',
      },
      {
        name: '1风单元',
        desc: '总计能量约2e19',
        data: 'eyJlbmVyZ3kiOiIxNTIuNTI1NDk5OTk5OTk5MTQiLCJlbmVyZ3l0dGwiOiIxNTguNTI1NDk5OTk5OTk5MSIsIndzY2IwMSI6IjEiLCJ3c2NiMDIiOiIxIiwid3NjYjAzIjoiMCIsIndzY2IwNCI6IjAiLCJ3c2NiMDUiOiIwIiwid3NjYjA2IjoiMCIsIndzY2IwNyI6IjAiLCJ3c2NiMDgiOiIwIiwid3NjYjA5IjoiMCIsIndzY2IxMCI6IjAiLCJ3c2NiMTEiOiIwIiwid3NjYjEyIjoiMCIsIndzY2IxMyI6IjAiLCJ3c2NiMTQiOiIwIiwid3NjYjE1IjoiMCIsIndzY2IxNiI6IjAiLCJ3c2NiMTciOiIwIiwid3NjYjE4IjoiMCIsIndzY2IxOSI6IjAiLCJ3c2NiMjAiOiIwIiwid3NjYjIxIjoiMCIsIndzY2IyMiI6IjAiLCJ3c2NiMjMiOiIwIiwid3NjYjI0IjoiMCIsIndzY2IyNSI6IjAiLCJ3c2NiMjYiOiIwIiwid3NjYjI3IjoiMCIsIndzY2IyOCI6IjAiLCJ3c2NiMjkiOiIwIiwid3NjYjMwIjoiMCIsIndzY2IzMSI6IjAiLCJ3c2NiMzIiOiIwIiwid3NjYjMzIjoiMCIsIndzY2IzNCI6IjAiLCJ3c2NiMzUiOiIwIiwid3NjYjM2IjoiMCIsIndzY2IzNyI6IjAiLCJ3c2NiMzgiOiIwIiwid3NjYjM5IjoiMCIsIndzY2I0MCI6IjAiLCJ3c2NhMDEiOiIxNy40MTI0OTk5OTk5OTk5Iiwid3NjYTAyIjoiMSIsIndzY2EwMyI6IjAiLCJ3c2NhMDQiOiIwIiwid3NjYTA1IjoiMCIsIndzY2EwNiI6IjAiLCJ3c2NhMDciOiIwIiwid3NjYTA4IjoiMCIsIndzY2EwOSI6IjAiLCJ3c2NhMTAiOiIwIiwid3NjYTExIjoiMCIsIndzY2ExMiI6IjAiLCJ3c2NhMTMiOiIwIiwid3NjYTE0IjoiMCIsIndzY2ExNSI6IjAiLCJ3c2NhMTYiOiIwIiwid3NjYTE3IjoiMCIsIndzY2ExOCI6IjAiLCJ3c2NhMTkiOiIwIiwid3NjYTIwIjoiMCIsIndzY2EyMSI6IjAiLCJ3c2NhMjIiOiIwIiwid3NjYTIzIjoiMCIsIndzY2EyNCI6IjAiLCJ3c2NhMjUiOiIwIiwid3NjYTI2IjoiMCIsIndzY2EyNyI6IjAiLCJ3c2NhMjgiOiIwIiwid3NjYTI5IjoiMCIsIndzY2EzMCI6IjAiLCJ3c2NhMzEiOiIwIiwid3NjYTMyIjoiMCIsIndzY2EzMyI6IjAiLCJ3c2NhMzQiOiIwIiwid3NjYTM1IjoiMCIsIndzY2EzNiI6IjAiLCJ3c2NhMzciOiIwIiwid3NjYTM4IjoiMCIsIndzY2EzOSI6IjAiLCJ3c2NhNDAiOiIwIiwidGllcjAxIjoiMSIsInRpZXIwMiI6IjAiLCJ0aWVyMDMiOiIwIiwidGllcjA0IjoiMCIsInRpZXIwMWNvbmYiOmZhbHNlLCJ0aWVyMDJjb25mIjpmYWxzZSwidGllcjAzY29uZiI6ZmFsc2UsInRpZXIwNGNvbmYiOmZhbHNlLCJhdXRvYnV5dGllcjAxIjpmYWxzZSwiYXV0b2J1eXRpZXIwMiI6ZmFsc2UsImF1dG9idXl0aWVyMDMiOmZhbHNlLCJhdXRvYnV5dGllcjA0IjpmYWxzZSwidXBnZDAxIjoiMCIsInVwZ2QwMiI6IjAiLCJ1cGdkMDMiOiIwIiwidXBnZDA0IjoiMCIsImF1dG9idXl1cGdkMDEiOmZhbHNlLCJhdXRvYnV5dXBnZDAyIjpmYWxzZSwiYXV0b2J1eXVwZ2QwMyI6ZmFsc2UsImF1dG9idXl1cGdkMDQiOmZhbHNlLCJoYXNVbmxvY2tlZFBMMSI6ZmFsc2UsIlBMMWVuZXJneSI6IjEiLCJQTDFwdHMiOiIwIiwiUEwxcHRzdG90YWwiOiIwIiwiaGFzVW5sb2NrZWRQTDIiOmZhbHNlLCJQTDJlbmVyZ3kiOiIxIiwiUEwycHRzIjoiMCIsIlBMMnB0c3RvdGFsIjoiMCIsImhhc1VubG9ja2VkUEwzIjpmYWxzZSwiUEwzZW5lcmd5IjoiMSIsIlBMM3B0cyI6IjAiLCJQTDNwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMNCI6ZmFsc2UsIlBMM2VuZXJneSI6IjEiLCJQTDRwdHMiOiIwIiwiUEw0cHRzdG90YWwiOiIwIiwiaGFzVW5sb2NrZWRQTDUiOmZhbHNlLCJQTDVlbmVyZ3kiOiIxIiwiUEw1cHRzIjoiMCIsIlB MNXB0c3RvdGFsIjoiMCIsImluY2hhIjowLCJjaGFjb20wMSI6IjAiLCJjaGFjb20wMiI6IjAiLCJjaGFjb20wMyI6IjAiLCJjaGFjb20wNCI6IjAiLCJjaGFjb20wNSI6IjAiLCJjaGFjb20wNiI6IjAiLCJjaGFjb20wNyI6IjAiLCJjaGFjb20wOCI6IjAiLCJjaGFjb20wOSI6IjAiLCJjaGFjb20xMCI6IjAiLCJjaGFjb20xMSI6IjAiLCJjaGFjb20xMiI6IjAiLCJjaGFjb20xMyI6IjAiLCJjaGFjb20xNCI6IjAiLCJjaGFjb20xNSI6IjAiLCJjaGFjb20xNiI6IjAiLCJjaGFjb20xNyI6IjAiLCJjaGFjb20xOCI6IjAiLCJjaGFjb20xOSI6IjAiLCJjaGFjb20yMCI6IjAiLCJjaGFjb20yMSI6IjAiLCJjaGFjb20yMiI6IjAiLCJjaGFjb20yMyI6IjAiLCJjaGFjb20yNCI6IjAiLCJoYXNVbmxvY2tlZENoYSI6ZmFsc2UsImFjaGV2ZSI6W10sImF1dG9Db25maXJtIjpmYWxzZSwibWF4QWxsIjpmYWxzZSwidGltZSI6MCwibGFzdFRpbWUiOjAsInZlcnNpb24iOiI2LjAuMCJ9',
        author: '6左爷6',
      },
      {
        name: '1风模块',
        desc: '总计能量约2e77',
        data: 'eyJlbmVyZ3kiOiI0LjU0MDY4MzU5Mzc0OTk3MiIsImVuZXJneXR0bCI6IjEwLjU0MDY4MzU5Mzc0OTk2NCIsIndzY2IwMSI6IjEiLCJ3c2NiMDIiOiIxIiwid3NjYjAzIjoiMCIsIndzY2IwNCI6IjAiLCJ3c2NiMDUiOiIwIiwid3NjYjA2IjoiMCIsIndzY2IwNyI6IjAiLCJ3c2NiMDgiOiIwIiwid3NjYjA5IjoiMCIsIndzY2IxMCI6IjAiLCJ3c2NiMTEiOiIwIiwid3NjYjEyIjoiMCIsIndzY2IxMyI6IjAiLCJ3c2NiMTQiOiIwIiwid3NjYjE1IjoiMCIsIndzY2IxNiI6IjAiLCJ3c2NiMTciOiIwIiwid3NjYjE4IjoiMCIsIndzY2IxOSI6IjAiLCJ3c2NiMjAiOiIwIiwid3NjYjIxIjoiMCIsIndzY2IyMiI6IjAiLCJ3c2NiMjMiOiIwIiwid3NjYjI0IjoiMCIsIndzY2IyNSI6IjAiLCJ3c2NiMjYiOiIwIiwid3NjYjI3IjoiMCIsIndzY2IyOCI6IjAiLCJ3c2NiMjkiOiIwIiwid3NjYjMwIjoiMCIsIndzY2IzMSI6IjAiLCJ3c2NiMzIiOiIwIiwid3NjYjMzIjoiMCIsIndzY2IzNCI6IjAiLCJ3c2NiMzUiOiIwIiwid3NjYjM2IjoiMCIsIndzY2IzNyI6IjAiLCJ3c2NiMzgiOiIwIiwid3NjYjM5IjoiMCIsIndzY2I0MCI6IjAiLCJ3c2NhMDEiOiIzLjA2MjQ5OTk5OTk5OTk4OTMiLCJ3c2NhMDIiOiIxIiwid3NjYTAzIjoiMCIsIndzY2EwNCI6IjAiLCJ3c2NhMDUiOiIwIiwid3NjYTA2IjoiMCIsIndzY2EwNyI6IjAiLCJ3c2NhMDgiOiIwIiwid3NjYTA5IjoiMCIsIndzY2ExMCI6IjAiLCJ3c2NhMTEiOiIwIiwid3NjYTEyIjoiMCIsIndzY2ExMyI6IjAiLCJ3c2NhMTQiOiIwIiwid3NjYTE1IjoiMCIsIndzY2ExNiI6IjAiLCJ3c2NhMTciOiIwIiwid3NjYTE4IjoiMCIsIndzY2ExOSI6IjAiLCJ3c2NhMjAiOiIwIiwid3NjYTIxIjoiMCIsIndzY2EyMiI6IjAiLCJ3c2NhMjMiOiIwIiwid3NjYTI0IjoiMCIsIndzY2EyNSI6IjAiLCJ3c2NhMjYiOiIwIiwid3NjYTI3IjoiMCIsIndzY2EyOCI6IjAiLCJ3c2NhMjkiOiIwIiwid3NjYTMwIjoiMCIsIndzY2EzMSI6IjAiLCJ3c2NhMzIiOiIwIiwid3NjYTMzIjoiMCIsIndzY2EzNCI6IjAiLCJ3c2NhMzUiOiIwIiwid3NjYTM2IjoiMCIsIndzY2EzNyI6IjAiLCJ3c2NhMzgiOiIwIiwid3NjYTM5IjoiMCIsIndzY2E0MCI6IjAiLCJ0aWVyMDEiOiIwIiwidGllcjAyIjoiMSIsInRpZXIwMyI6IjAiLCJ0aWVyMDQiOiIwIiwidGllcjAxY29uZiI6ZmFsc2UsInRpZXIwMmNvbmYiOmZhbHNlLCJ0aWVyMDNjb25mIjpmYWxzZSwidGllcjA0Y29uZiI6ZmFsc2UsImF1dG9idXl0aWVyMDEiOmZhbHNlLCJhdXRvYnV5dGllcjAyIjpmYWxzZSwiYXV0b2J1eXRpZXIwMyI6ZmFsc2UsImF1dG9idXl0aWVyMDQiOmZhbHNlLCJ1cGdkMDEiOiIwIiwidXBnZDAyIjoiMCIsInVwZ2QwMyI6IjAiLCJ1cGdkMDQiOiIwIiwiYXV0b2J1eXVwZ2QwMSI6ZmFsc2UsImF1dG9idXl1cGdkMDIiOmZhbHNlLCJhdXRvYnV5dXBnZDAzIjpmYWxzZSwiYXV0b2J1eXVwZ2QwNCI6ZmFsc2UsImhhc1VubG9ja2VkUEwxIjpmYWxzZSwiUEwxZW5lcmd5IjoiMSIsIlBMMXB0cyI6IjAiLCJQTDFwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMMiI6ZmFsc2UsIlBMMmVuZXJneSI6IjEiLCJQTDJwdHMiOiIwIiwiUEwycHRzdG90YWwiOiIwIiwiaGFzVW5sb2NrZWRQTDMiOmZhbHNlLCJQTDNlbmVyZ3kiOiIxIiwiUEwzcHRzIjoiMCIsIlBMM3B0c3RvdGFsIjoiMCIsImhhc1VubG9ja2VkUEw0IjpmYWxzZSwiUEwzZW5lcmd5IjoiMSIsIlB MNHB0cyI6IjAiLCJQTDRwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMNSI6ZmFsc2UsIlB MNWVuZXJneSI6IjEiLCJQTDVwdHMiOiIwIiwiUEw1cHRzdG90YWwiOiIwIiwiaW5jaGEiOjAsImNoYWNvbTAxIjoiMCIsImNoYWNvbTAyIjoiMCIsImNoYWNvbTAzIjoiMCIsImNoYWNvbTA0IjoiMCIsImNoYWNvbTA1IjoiMCIsImNoYWNvbTA2IjoiMCIsImNoYWNvbTA3IjoiMCIsImNoYWNvbTA4IjoiMCIsImNoYWNvbTA5IjoiMCIsImNoYWNvbTEwIjoiMCIsImNoYWNvbTExIjoiMCIsImNoYWNvbTEyIjoiMCIsImNoYWNvbTEzIjoiMCIsImNoYWNvbTE0IjoiMCIsImNoYWNvbTE1IjoiMCIsImNoYWNvbTE2IjoiMCIsImNoYWNvbTE3IjoiMCIsImNoYWNvbTE4IjoiMCIsImNoYWNvbTE5IjoiMCIsImNoYWNvbTIwIjoiMCIsImNoYWNvbTIxIjoiMCIsImNoYWNvbTIyIjoiMCIsImNoYWNvbTIzIjoiMCIsImNoYWNvbTI0IjoiMCIsImhhc1VubG9ja2VkQ2hhIjpmYWxzZSwiYWNoZXZlIjpbXSwiYXV0b0NvbmZpcm0iOmZhbHNlLCJtYXhBbGwiOmZhbHNlLCJ0aW1lIjowLCJsYXN0VGltZSI6MCwidmVyc2lvbiI6IjYuMC4wIn0=',
        author: '6左爷6',
      },
      {
        name: '扩散前阶段',
        desc: '总计能量约1.8e308',
        data: '1145eyJlbmVyZ3kiOiIxLjM1MDE3MzQ2MTQxMTk4MzZlMjU2IiwiZW5lcmd5dHRsIjoiMS43MjU1NDkzMDI4NTE5OTE3ZTI1NiIsIndzY2IwMSI6IjQyNCIsIndzY2IwMiI6IjIxMiIsIndzY2IwMyI6IjEwNiIsIndzY2IwNCI6IjUzIiwid3NjYjA1IjoiMjciLCJ3c2NiMDYiOiIxMyIsIndzY2IwNyI6IjciLCJ3c2NiMDgiOiIzIiwid3NjYjA5IjoiMCIsIndzY2IxMCI6IjAiLCJ3c2NiMTEiOiIwIiwid3NjYjEyIjoiMCIsIndzY2IxMyI6IjAiLCJ3c2NiMTQiOiIwIiwid3NjYjE1IjoiMCIsIndzY2IxNiI6IjAiLCJ3c2NiMTciOiIwIiwid3NjYjE4IjoiMCIsIndzY2IxOSI6IjAiLCJ3c2NiMjAiOiIwIiwid3NjYjIxIjoiMCIsIndzY2IyMiI6IjAiLCJ3c2NiMjMiOiIwIiwid3NjYjI0IjoiMCIsIndzY2IyNSI6IjAiLCJ3c2NiMjYiOiIwIiwid3NjYjI3IjoiMCIsIndzY2IyOCI6IjAiLCJ3c2NiMjkiOiIwIiwid3NjYjMwIjoiMCIsIndzY2IzMSI6IjAiLCJ3c2NiMzIiOiIwIiwid3NjYjMzIjoiMCIsIndzY2IzNCI6IjAiLCJ3c2NiMzUiOiIwIiwid3NjYjM2IjoiMCIsIndzY2IzNyI6IjAiLCJ3c2NiMzgiOiIwIiwid3NjYjM5IjoiMCIsIndzY2I0MCI6IjAiLCJ3c2NhMDEiOiIyLjIzMjQ2MTk1MzAwNDU3NDZlMTQ3Iiwid3NjYTAyIjoiOS41NDQ2NTc4MDkwODk5MjhlODkiLCJ3c2NhMDMiOiIxLjgzMzI2NDUxMTM1NjA1MDZlNTgiLCJ3c2NhMDQiOiIxLjkxNDkxMzQ5NzYwNzI2MzNlMzkiLCJ3c2NhMDUiOiIzLjU3NjI4MDE3NTM3OTkyNjNlMjYiLCJ3c2NhMDYiOiI3LjAxNTc5NDI1MjM1MjgwODVlMTYiLCJ3c2NhMDciOiIyNjE3Njc0NjcuMzc4MjQwNCIsIndzY2EwOCI6IjMiLCJ3c2NhMDkiOiIwIiwid3NjYTEwIjoiMCIsIndzY2ExMSI6IjAiLCJ3c2NhMTIiOiIwIiwid3NjYTEzIjoiMCIsIndzY2ExNCI6IjAiLCJ3c2NhMTUiOiIwIiwid3NjYTE2IjoiMCIsIndzY2ExNyI6IjAiLCJ3c2NhMTgiOiIwIiwid3NjYTE5IjoiMCIsIndzY2EyMCI6IjAiLCJ3c2NhMjEiOiIwIiwid3NjYTIyIjoiMCIsIndzY2EyMyI6IjAiLCJ3c2NhMjQiOiIwIiwid3NjYTI1IjoiMCIsIndzY2EyNiI6IjAiLCJ3c2NhMjciOiIwIiwid3NjYTI4IjoiMCIsIndzY2EyOSI6IjAiLCJ3c2NhMzAiOiIwIiwid3NjYTMxIjoiMCIsIndzY2EzMiI6IjAiLCJ3c2NhMzMiOiIwIiwid3NjYTM0IjoiMCIsIndzY2EzNSI6IjAiLCJ3c2NhMzYiOiIwIiwid3NjYTM3IjoiMCIsIndzY2EzOCI6IjAiLCJ3c2NhMzkiOiIwIiwid3NjYTQwIjoiMCIsInRpZXIwMSI6IjE1IiwidGllcjAyIjoiMyIsInRpZXIwMyI6IjAiLCJ0aWVyMDQiOiIwIiwidGllcjAxY29uZiI6ZmFsc2UsInRpZXIwMmNvbmYiOmZhbHNlLCJ0aWVyMDNjb25mIjpmYWxzZSwidGllcjA0Y29uZiI6ZmFsc2UsImF1dG9idXl0aWVyMDEiOmZhbHNlLCJhdXRvYnV5dGllcjAyIjpmYWxzZSwiYXV0b2J1eXRpZXIwMyI6ZmFsc2UsImF1dG9idXl0aWVyMDQiOmZhbHNlLCJ1cGdkMDEiOiIwIiwidXBnZDAyIjoiMCIsInVwZ2QwMyI6IjAiLCJ1cGdkMDQiOiIwIiwiYXV0b2J1eXVwZ2QwMSI6ZmFsc2UsImF1dG9idXl1cGdkMDIiOmZhbHNlLCJhdXRvYnV5dXBnZDAzIjpmYWxzZSwiYXV0b2J1eXVwZ2QwNCI6ZmFsc2UsImhhc1VubG9ja2VkUEwxIjpmYWxzZSwiUEwxZW5lcmd5IjoiMSIsIlBMMXB0cyI6IjAiLCJQTDFwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMMiI6ZmFsc2UsIlBMMmVuZXJneSI6IjEiLCJQTDJwdHMiOiIwIiwiUEwycHRzdG90YWwiOiIwIiwiaGFzVW5sb2NrZWRQTDMiOmZhbHNlLCJQTDNlbmVyZ3kiOiIxIiwiUEwzcHRzIjoiMCIsIlBMM3B0c3RvdGFsIjoiMCIsImhhc1VubG9ja2VkUEw0IjpmYWxzZSwiUEwzZW5lcmd5IjoiMSIsIlB MNHB0cyI6IjAiLCJQTDRwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMNSI6ZmFsc2UsIlB MNWVuZXJneSI6IjEiLCJQTDVwdHMiOiIwIiwiUEw1cHRzdG90YWwiOiIwIiwiaW5jaGEiOjAsImNoYWNvbTAxIjoiMCIsImNoYWNvbTAyIjoiMCIsImNoYWNvbTAzIjoiMCIsImNoYWNvbTA0IjoiMCIsImNoYWNvbTA1IjoiMCIsImNoYWNvbTA2IjoiMCIsImNoYWNvbTA3IjoiMCIsImNoYWNvbTA4IjoiMCIsImNoYWNvbTA5IjoiMCIsImNoYWNvbTEwIjoiMCIsImNoYWNvbTExIjoiMCIsImNoYWNvbTEyIjoiMCIsImNoYWNvbTEzIjoiMCIsImNoYWNvbTE0IjoiMCIsImNoYWNvbTE1IjoiMCIsImNoYWNvbTE2IjoiMCIsImNoYWNvbTE3IjoiMCIsImNoYWNvbTE4IjoiMCIsImNoYWNvbTE5IjoiMCIsImNoYWNvbTIwIjoiMCIsImNoYWNvbTIxIjoiMCIsImNoYWNvbTIyIjoiMCIsImNoYWNvbTIzIjoiMCIsImNoYWNvbTI0IjoiMCIsImhhc1VubG9ja2VkQ2hhIjpmYWxzZSwiYWNoZXZlIjpbXSwiYXV0b0NvbmZpcm0iOmZhbHNlLCJtYXhBbGwiOmZhbHNlLCJ0aW1lIjowLCJsYXN0VGltZSI6MCwidmVyc2lvbiI6IjYuMC4wIn0=',
        author: '6左爷6',
      },
    ]
  },
  {
    name: '扩散阶段',
    styles: 'background-color: #ff0000; font-size: 24px',
    saves: [
      {
        name: '第一次扩散',
        desc: '2^2^10能量',
        data: 'eyJlbmVyZ3kiOiIyIiwiZW5lcmd5dHRsIjoiMiIsIndzY2IwMSI6IjAiLCJ3c2NiMDIiOiIwIiwid3NjYjAzIjoiMCIsIndzY2IwNCI6IjAiLCJ3c2NiMDUiOiIwIiwid3NjYjA2IjoiMCIsIndzY2IwNyI6IjAiLCJ3c2NiMDgiOiIwIiwid3NjYjA5IjoiMCIsIndzY2IxMCI6IjAiLCJ3c2NiMTEiOiIwIiwid3NjYjEyIjoiMCIsIndzY2IxMyI6IjAiLCJ3c2NiMTQiOiIwIiwid3NjYjE1IjoiMCIsIndzY2IxNiI6IjAiLCJ3c2NiMTciOiIwIiwid3NjYjE4IjoiMCIsIndzY2IxOSI6IjAiLCJ3c2NiMjAiOiIwIiwid3NjYjIxIjoiMCIsIndzY2IyMiI6IjAiLCJ3c2NiMjMiOiIwIiwid3NjYjI0IjoiMCIsIndzY2IyNSI6IjAiLCJ3c2NiMjYiOiIwIiwid3NjYjI3IjoiMCIsIndzY2IyOCI6IjAiLCJ3c2NiMjkiOiIwIiwid3NjYjMwIjoiMCIsIndzY2IzMSI6IjAiLCJ3c2NiMzIiOiIwIiwid3NjYjMzIjoiMCIsIndzY2IzNCI6IjAiLCJ3c2NiMzUiOiIwIiwid3NjYjM2IjoiMCIsIndzY2IzNyI6IjAiLCJ3c2NiMzgiOiIwIiwid3NjYjM5IjoiMCIsIndzY2I0MCI6IjAiLCJ3c2NhMDEiOiIwIiwid3NjYTAyIjoiMCIsIndzY2EwMyI6IjAiLCJ3c2NhMDQiOiIwIiwid3NjYTA1IjoiMCIsIndzY2EwNiI6IjAiLCJ3c2NhMDciOiIwIiwid3NjYTA4IjoiMCIsIndzY2EwOSI6IjAiLCJ3c2NhMTAiOiIwIiwid3NjYTExIjoiMCIsIndzY2ExMiI6IjAiLCJ3c2NhMTMiOiIwIiwid3NjYTE0IjoiMCIsIndzY2ExNSI6IjAiLCJ3c2NhMTYiOiIwIiwid3NjYTE3IjoiMCIsIndzY2ExOCI6IjAiLCJ3c2NhMTkiOiIwIiwid3NjYTIwIjoiMCIsIndzY2EyMSI6IjAiLCJ3c2NhMjIiOiIwIiwid3NjYTIzIjoiMCIsIndzY2EyNCI6IjAiLCJ3c2NhMjUiOiIwIiwid3NjYTI2IjoiMCIsIndzY2EyNyI6IjAiLCJ3c2NhMjgiOiIwIiwid3NjYTI5IjoiMCIsIndzY2EzMCI6IjAiLCJ3c2NhMzEiOiIwIiwid3NjYTMyIjoiMCIsIndzY2EzMyI6IjAiLCJ3c2NhMzQiOiIwIiwid3NjYTM1IjoiMCIsIndzY2EzNiI6IjAiLCJ3c2NhMzciOiIwIiwid3NjYTM4IjoiMCIsIndzY2EzOSI6IjAiLCJ3c2NhNDAiOiIwIiwidGllcjAxIjoiMCIsInRpZXIwMiI6IjAiLCJ0aWVyMDMiOiIwIiwidGllcjA0IjoiMCIsInRpZXIwMWNvbmYiOmZhbHNlLCJ0aWVyMDJjb25mIjpmYWxzZSwidGllcjAzY29uZiI6ZmFsc2UsInRpZXIwNGNvbmYiOmZhbHNlLCJhdXRvYnV5dGllcjAxIjpmYWxzZSwiYXV0b2J1eXRpZXIwMiI6ZmFsc2UsImF1dG9idXl0aWVyMDMiOmZhbHNlLCJhdXRvYnV5dGllcjA0IjpmYWxzZSwidXBnZDAxIjoiMCIsInVwZ2QwMiI6IjAiLCJ1cGdkMDMiOiIwIiwidXBnZDA0IjoiMCIsImF1dG9idXl1cGdkMDEiOmZhbHNlLCJhdXRvYnV5dXBnZDAyIjpmYWxzZSwiYXV0b2J1eXVwZ2QwMyI6ZmFsc2UsImF1dG9idXl1cGdkMDQiOmZhbHNlLCJoYXNVbmxvY2tlZFBMMSI6dHJ1ZSwiUEwxZW5lcmd5IjoiMSIsIlBMMXB0cyI6IjIiLCJQTDFwdHN0b3RhbCI6IjIiLCJoYXNVbmxvY2tlZFBMMiI6ZmFsc2UsIlBMMmVuZXJneSI6IjEiLCJQTDJwdHMiOiIwIiwiUEwycHRzdG90YWwiOiIwIiwiaGFzVW5sb2NrZWRQTDMiOmZhbHNlLCJQTDNlbmVyZ3kiOiIxIiwiUEwzcHRzIjoiMCIsIlBMM3B0c3RvdGFsIjoiMCIsImhhc1VubG9ja2VkUEw0IjpmYWxzZSwiUEwzZW5lcmd5IjoiMSIsIlB MNHB0cyI6IjAiLCJQTDRwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMNSI6ZmFsc2UsIlB MNWVuZXJneSI6IjEiLCJQTDVwdHMiOiIwIiwiUEw1cHRzdG90YWwiOiIwIiwiaW5jaGEiOjAsImNoYWNvbTAxIjoiMCIsImNoYWNvbTAyIjoiMCIsImNoYWNvbTAzIjoiMCIsImNoYWNvbTA0IjoiMCIsImNoYWNvbTA1IjoiMCIsImNoYWNvbTA2IjoiMCIsImNoYWNvbTA3IjoiMCIsImNoYWNvbTA4IjoiMCIsImNoYWNvbTA5IjoiMCIsImNoYWNvbTEwIjoiMCIsImNoYWNvbTExIjoiMCIsImNoYWNvbTEyIjoiMCIsImNoYWNvbTEzIjoiMCIsImNoYWNvbTE0IjoiMCIsImNoYWNvbTE1IjoiMCIsImNoYWNvbTE2IjoiMCIsImNoYWNvbTE3IjoiMCIsImNoYWNvbTE4IjoiMCIsImNoYWNvbTE5IjoiMCIsImNoYWNvbTIwIjoiMCIsImNoYWNvbTIxIjoiMCIsImNoYWNvbTIyIjoiMCIsImNoYWNvbTIzIjoiMCIsImNoYWNvbTI0IjoiMCIsImhhc1VubG9ja2VkQ2hhIjpmYWxzZSwiYWNoZXZlIjpbXSwiYXV0b0NvbmZpcm0iOmZhbHNlLCJtYXhBbGwiOmZhbHNlLCJ0aW1lIjowLCJsYXN0VGltZSI6MCwidmVyc2lvbiI6IjYuMC4wIn0=',
        author: '6左爷6',
      },
    ]
  },
  {
    name: '扪敤阶段',
    styles: 'background-color: #ffff00; color: #000000; font-size: 24px',
    saves: [
      {
        name: '第一次扪敤',
        desc: '2^2^20能量',
        data: 'eyJlbmVyZ3kiOiIyIiwiZW5lcmd5dHRsIjoiMiIsIndzY2IwMSI6IjAiLCJ3c2NiMDIiOiIwIiwid3NjYjAzIjoiMCIsIndzY2IwNCI6IjAiLCJ3c2NiMDUiOiIwIiwid3NjYjA2IjoiMCIsIndzY2IwNyI6IjAiLCJ3c2NiMDgiOiIwIiwid3NjYjA5IjoiMCIsIndzY2IxMCI6IjAiLCJ3c2NiMTEiOiIwIiwid3NjYjEyIjoiMCIsIndzY2IxMyI6IjAiLCJ3c2NiMTQiOiIwIiwid3NjYjE1IjoiMCIsIndzY2IxNiI6IjAiLCJ3c2NiMTciOiIwIiwid3NjYjE4IjoiMCIsIndzY2IxOSI6IjAiLCJ3c2NiMjAiOiIwIiwid3NjYjIxIjoiMCIsIndzY2IyMiI6IjAiLCJ3c2NiMjMiOiIwIiwid3NjYjI0IjoiMCIsIndzY2IyNSI6IjAiLCJ3c2NiMjYiOiIwIiwid3NjYjI3IjoiMCIsIndzY2IyOCI6IjAiLCJ3c2NiMjkiOiIwIiwid3NjYjMwIjoiMCIsIndzY2IzMSI6IjAiLCJ3c2NiMzIiOiIwIiwid3NjYjMzIjoiMCIsIndzY2IzNCI6IjAiLCJ3c2NiMzUiOiIwIiwid3NjYjM2IjoiMCIsIndzY2IzNyI6IjAiLCJ3c2NiMzgiOiIwIiwid3NjYjM5IjoiMCIsIndzY2I0MCI6IjAiLCJ3c2NhMDEiOiIwIiwid3NjYTAyIjoiMCIsIndzY2EwMyI6IjAiLCJ3c2NhMDQiOiIwIiwid3NjYTA1IjoiMCIsIndzY2EwNiI6IjAiLCJ3c2NhMDciOiIwIiwid3NjYTA4IjoiMCIsIndzY2EwOSI6IjAiLCJ3c2NhMTAiOiIwIiwid3NjYTExIjoiMCIsIndzY2ExMiI6IjAiLCJ3c2NhMTMiOiIwIiwid3NjYTE0IjoiMCIsIndzY2ExNSI6IjAiLCJ3c2NhMTYiOiIwIiwid3NjYTE3IjoiMCIsIndzY2ExOCI6IjAiLCJ3c2NhMTkiOiIwIiwid3NjYTIwIjoiMCIsIndzY2EyMSI6IjAiLCJ3c2NhMjIiOiIwIiwid3NjYTIzIjoiMCIsIndzY2EyNCI6IjAiLCJ3c2NhMjUiOiIwIiwid3NjYTI2IjoiMCIsIndzY2EyNyI6IjAiLCJ3c2NhMjgiOiIwIiwid3NjYTI5IjoiMCIsIndzY2EzMCI6IjAiLCJ3c2NhMzEiOiIwIiwid3NjYTMyIjoiMCIsIndzY2EzMyI6IjAiLCJ3c2NhMzQiOiIwIiwid3NjYTM1IjoiMCIsIndzY2EzNiI6IjAiLCJ3c2NhMzciOiIwIiwid3NjYTM4IjoiMCIsIndzY2EzOSI6IjAiLCJ3c2NhNDAiOiIwIiwidGllcjAxIjoiMCIsInRpZXIwMiI6IjAiLCJ0aWVyMDMiOiIwIiwidGllcjA0IjoiMCIsInRpZXIwMWNvbmYiOmZhbHNlLCJ0aWVyMDJjb25mIjpmYWxzZSwidGllcjAzY29uZiI6ZmFsc2UsInRpZXIwNGNvbmYiOmZhbHNlLCJhdXRvYnV5dGllcjAxIjpmYWxzZSwiYXV0b2J1eXRpZXIwMiI6ZmFsc2UsImF1dG9idXl0aWVyMDMiOmZhbHNlLCJhdXRvYnV5dGllcjA0IjpmYWxzZSwidXBnZDAxIjoiMCIsInVwZ2QwMiI6IjAiLCJ1cGdkMDMiOiIwIiwidXBnZDA0IjoiMCIsImF1dG9idXl1cGdkMDEiOmZhbHNlLCJhdXRvYnV5dXBnZDAyIjpmYWxzZSwiYXV0b2J1eXVwZ2QwMyI6ZmFsc2UsImF1dG9idXl1cGdkMDQiOmZhbHNlLCJoYXNVbmxvY2tlZFBMMSI6dHJ1ZSwiUEwxZW5lcmd5IjoiMSIsIlBMMXB0cyI6IjAiLCJQTDFwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMMiI6dHJ1ZSwiUEwyZW5lcmd5IjoiMSIsIlBMMnB0cyI6IjIiLCJQTDJwdHN0b3RhbCI6IjIiLCJoYXNVbmxvY2tlZFBMMyI6ZmFsc2UsIlBMM2VuZXJneSI6IjEiLCJQTDNwdHMiOiIwIiwiUEwzcHRzdG90YWwiOiIwIiwiaGFzVW5sb2NrZWRQTDA0IjpmYWxzZSwiUEw0ZW5lcmd5IjoiMSIsIlB MNHB0cyI6IjAiLCJQTDRwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMNSI6ZmFsc2UsIlB MNWVuZXJneSI6IjEiLCJQTDVwdHMiOiIwIiwiUEw1cHRzdG90YWwiOiIwIiwiaW5jaGEiOjAsImNoYWNvbTAxIjoiMCIsImNoYWNvbTAyIjoiMCIsImNoYWNvbTAzIjoiMCIsImNoYWNvbTA0IjoiMCIsImNoYWNvbTA1IjoiMCIsImNoYWNvbTA2IjoiMCIsImNoYWNvbTA3IjoiMCIsImNoYWNvbTA4IjoiMCIsImNoYWNvbTA5IjoiMCIsImNoYWNvbTEwIjoiMCIsImNoYWNvbTExIjoiMCIsImNoYWNvbTEyIjoiMCIsImNoYWNvbTEzIjoiMCIsImNoYWNvbTE0IjoiMCIsImNoYWNvbTE1IjoiMCIsImNoYWNvbTE2IjoiMCIsImNoYWNvbTE3IjoiMCIsImNoYWNvbTE4IjoiMCIsImNoYWNvbTE5IjoiMCIsImNoYWNvbTIwIjoiMCIsImNoYWNvbTIxIjoiMCIsImNoYWNvbTIyIjoiMCIsImNoYWNvbTIzIjoiMCIsImNoYWNvbTI0IjoiMCIsImhhc1VubG9ja2VkQ2hhIjpmYWxzZSwiYWNoZXZlIjpbXSwiYXV0b0NvbmZpcm0iOmZhbHNlLCJtYXhBbGwiOmZhbHNlLCJ0aW1lIjowLCJsYXN0VGltZSI6MCwidmVyc2lvbiI6IjYuMC4wIn0=',
        author: '6左爷6',
      },
    ]
  },
  {
    name: '扫敥阶段',
    styles: 'background-color: #00ff00; color: #000000; font-size: 24px',
    saves: [
      {
        name: '第一次扫敥',
        desc: '2^2^40能量',
        data: 'eyJlbmVyZ3kiOiIyIiwiZW5lcmd5dHRsIjoiMiIsIndzY2IwMSI6IjAiLCJ3c2NiMDIiOiIwIiwid3NjYjAzIjoiMCIsIndzY2IwNCI6IjAiLCJ3c2NiMDUiOiIwIiwid3NjYjA2IjoiMCIsIndzY2IwNyI6IjAiLCJ3c2NiMDgiOiIwIiwid3NjYjA5IjoiMCIsIndzY2IxMCI6IjAiLCJ3c2NiMTEiOiIwIiwid3NjYjEyIjoiMCIsIndzY2IxMyI6IjAiLCJ3c2NiMTQiOiIwIiwid3NjYjE1IjoiMCIsIndzY2IxNiI6IjAiLCJ3c2NiMTciOiIwIiwid3NjYjE4IjoiMCIsIndzY2IxOSI6IjAiLCJ3c2NiMjAiOiIwIiwid3NjYjIxIjoiMCIsIndzY2IyMiI6IjAiLCJ3c2NiMjMiOiIwIiwid3NjYjI0IjoiMCIsIndzY2IyNSI6IjAiLCJ3c2NiMjYiOiIwIiwid3NjYjI3IjoiMCIsIndzY2IyOCI6IjAiLCJ3c2NiMjkiOiIwIiwid3NjYjMwIjoiMCIsIndzY2IzMSI6IjAiLCJ3c2NiMzIiOiIwIiwid3NjYjMzIjoiMCIsIndzY2IzNCI6IjAiLCJ3c2NiMzUiOiIwIiwid3NjYjM2IjoiMCIsIndzY2IzNyI6IjAiLCJ3c2NiMzgiOiIwIiwid3NjYjM5IjoiMCIsIndzY2I0MCI6IjAiLCJ3c2NhMDEiOiIwIiwid3NjYTAyIjoiMCIsIndzY2EwMyI6IjAiLCJ3c2NhMDQiOiIwIiwid3NjYTA1IjoiMCIsIndzY2EwNiI6IjAiLCJ3c2NhMDciOiIwIiwid3NjYTA4IjoiMCIsIndzY2EwOSI6IjAiLCJ3c2NhMTAiOiIwIiwid3NjYTExIjoiMCIsIndzY2ExMiI6IjAiLCJ3c2NhMTMiOiIwIiwid3NjYTE0IjoiMCIsIndzY2ExNSI6IjAiLCJ3c2NhMTYiOiIwIiwid3NjYTE3IjoiMCIsIndzY2ExOCI6IjAiLCJ3c2NhMTkiOiIwIiwid3NjYTIwIjoiMCIsIndzY2EyMSI6IjAiLCJ3c2NhMjIiOiIwIiwid3NjYTIzIjoiMCIsIndzY2EyNCI6IjAiLCJ3c2NhMjUiOiIwIiwid3NjYTI2IjoiMCIsIndzY2EyNyI6IjAiLCJ3c2NhMjgiOiIwIiwid3NjYTI5IjoiMCIsIndzY2EzMCI6IjAiLCJ3c2NhMzEiOiIwIiwid3NjYTMyIjoiMCIsIndzY2EzMyI6IjAiLCJ3c2NhMzQiOiIwIiwid3NjYTM1IjoiMCIsIndzY2EzNiI6IjAiLCJ3c2NhMzciOiIwIiwid3NjYTM4IjoiMCIsIndzY2EzOSI6IjAiLCJ3c2NhNDAiOiIwIiwidGllcjAxIjoiMCIsInRpZXIwMiI6IjAiLCJ0aWVyMDMiOiIwIiwidGllcjA0IjoiMCIsInRpZXIwMWNvbmYiOmZhbHNlLCJ0aWVyMDJjb25mIjpmYWxzZSwidGllcjAzY29uZiI6ZmFsc2UsInRpZXIwNGNvbmYiOmZhbHNlLCJhdXRvYnV5dGllcjAxIjpmYWxzZSwiYXV0b2J1eXRpZXIwMiI6ZmFsc2UsImF1dG9idXl0aWVyMDMiOmZhbHNlLCJhdXRvYnV5dGllcjA0IjpmYWxzZSwidXBnZDAxIjoiMCIsInVwZ2QwMiI6IjAiLCJ1cGdkMDMiOiIwIiwidXBnZDA0IjoiMCIsImF1dG9idXl1cGdkMDEiOmZhbHNlLCJhdXRvYnV5dXBnZDAyIjpmYWxzZSwiYXV0b2J1eXVwZ2QwMyI6ZmFsc2UsImF1dG9idXl1cGdkMDQiOmZhbHNlLCJoYXNVbmxvY2tlZFBMMSI6dHJ1ZSwiUEwxZW5lcmd5IjoiMSIsIlBMMXB0cyI6IjAiLCJQTDFwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMMiI6dHJ1ZSwiUEwyZW5lcmd5IjoiMSIsIlBMMnB0cyI6IjAiLCJQTDJwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMMyI6dHJ1ZSwiUEwzZW5lcmd5IjoiMSIsIlBMM3B0cyI6IjIiLCJQTDNwdHN0b3RhbCI6IjIiLCJoYXNVbmxvY2tlZFBMNCI6ZmFsc2UsIlB MNHB0cyI6IjAiLCJQTDRwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMNSI6ZmFsc2UsIlB MNWVuZXJneSI6IjEiLCJQTDVwdHMiOiIwIiwiUEw1cHRzdG90YWwiOiIwIiwiaW5jaGEiOjAsImNoYWNvbTAxIjoiMCIsImNoYWNvbTAyIjoiMCIsImNoYWNvbTAzIjoiMCIsImNoYWNvbTA0IjoiMCIsImNoYWNvbTA1IjoiMCIsImNoYWNvbTA2IjoiMCIsImNoYWNvbTA3IjoiMCIsImNoYWNvbTA4IjoiMCIsImNoYWNvbTA5IjoiMCIsImNoYWNvbTEwIjoiMCIsImNoYWNvbTExIjoiMCIsImNoYWNvbTEyIjoiMCIsImNoYWNvbTEzIjoiMCIsImNoYWNvbTE0IjoiMCIsImNoYWNvbTE1IjoiMCIsImNoYWNvbTE2IjoiMCIsImNoYWNvbTE3IjoiMCIsImNoYWNvbTE4IjoiMCIsImNoYWNvbTE5IjoiMCIsImNoYWNvbTIwIjoiMCIsImNoYWNvbTIxIjoiMCIsImNoYWNvbTIyIjoiMCIsImNoYWNvbTIzIjoiMCIsImNoYWNvbTI0IjoiMCIsImhhc1VubG9ja2VkQ2hhIjpmYWxzZSwiYWNoZXZlIjpbXSwiYXV0b0NvbmZpcm0iOmZhbHNlLCJtYXhBbGwiOmZhbHNlLCJ0aW1lIjowLCJsYXN0VGltZSI6MCwidmVyc2lvbiI6IjYuMC4wIn0=',
        author: '6左爷6',
      },
    ]
  },
  {
    name: '扬敦阶段',
    styles: 'background-color: #00ffff; color: #000000; font-size: 24px',
    saves: [
      {
        name: '第一次扬敦',
        desc: '2^2^60能量',
        data: 'eyJlbmVyZ3kiOiIyIiwiZW5lcmd5dHRsIjoiMiIsIndzY2IwMSI6IjAiLCJ3c2NiMDIiOiIwIiwid3NjYjAzIjoiMCIsIndzY2IwNCI6IjAiLCJ3c2NiMDUiOiIwIiwid3NjYjA2IjoiMCIsIndzY2IwNyI6IjAiLCJ3c2NiMDgiOiIwIiwid3NjYjA5IjoiMCIsIndzY2IxMCI6IjAiLCJ3c2NiMTEiOiIwIiwid3NjYjEyIjoiMCIsIndzY2IxMyI6IjAiLCJ3c2NiMTQiOiIwIiwid3NjYjE1IjoiMCIsIndzY2IxNiI6IjAiLCJ3c2NiMTciOiIwIiwid3NjYjE4IjoiMCIsIndzY2IxOSI6IjAiLCJ3c2NiMjAiOiIwIiwid3NjYjIxIjoiMCIsIndzY2IyMiI6IjAiLCJ3c2NiMjMiOiIwIiwid3NjYjI0IjoiMCIsIndzY2IyNSI6IjAiLCJ3c2NiMjYiOiIwIiwid3NjYjI3IjoiMCIsIndzY2IyOCI6IjAiLCJ3c2NiMjkiOiIwIiwid3NjYjMwIjoiMCIsIndzY2IzMSI6IjAiLCJ3c2NiMzIiOiIwIiwid3NjYjMzIjoiMCIsIndzY2IzNCI6IjAiLCJ3c2NiMzUiOiIwIiwid3NjYjM2IjoiMCIsIndzY2IzNyI6IjAiLCJ3c2NiMzgiOiIwIiwid3NjYjM5IjoiMCIsIndzY2I0MCI6IjAiLCJ3c2NhMDEiOiIwIiwid3NjYTAyIjoiMCIsIndzY2EwMyI6IjAiLCJ3c2NhMDQiOiIwIiwid3NjYTA1IjoiMCIsIndzY2EwNiI6IjAiLCJ3c2NhMDciOiIwIiwid3NjYTA4IjoiMCIsIndzY2EwOSI6IjAiLCJ3c2NhMTAiOiIwIiwid3NjYTExIjoiMCIsIndzY2ExMiI6IjAiLCJ3c2NhMTMiOiIwIiwid3NjYTE0IjoiMCIsIndzY2ExNSI6IjAiLCJ3c2NhMTYiOiIwIiwid3NjYTE3IjoiMCIsIndzY2ExOCI6IjAiLCJ3c2NhMTkiOiIwIiwid3NjYTIwIjoiMCIsIndzY2EyMSI6IjAiLCJ3c2NhMjIiOiIwIiwid3NjYTIzIjoiMCIsIndzY2EyNCI6IjAiLCJ3c2NhMjUiOiIwIiwid3NjYTI2IjoiMCIsIndzY2EyNyI6IjAiLCJ3c2NhMjgiOiIwIiwid3NjYTI5IjoiMCIsIndzY2EzMCI6IjAiLCJ3c2NhMzEiOiIwIiwid3NjYTMyIjoiMCIsIndzY2EzMyI6IjAiLCJ3c2NhMzQiOiIwIiwid3NjYTM1IjoiMCIsIndzY2EzNiI6IjAiLCJ3c2NhMzciOiIwIiwid3NjYTM4IjoiMCIsIndzY2EzOSI6IjAiLCJ3c2NhNDAiOiIwIiwidGllcjAxIjoiMCIsInRpZXIwMiI6IjAiLCJ0aWVyMDMiOiIwIiwidGllcjA0IjoiMCIsInRpZXIwMWNvbmYiOmZhbHNlLCJ0aWVyMDJjb25mIjpmYWxzZSwidGllcjAzY29uZiI6ZmFsc2UsInRpZXIwNGNvbmYiOmZhbHNlLCJhdXRvYnV5dGllcjAxIjpmYWxzZSwiYXV0b2J1eXRpZXIwMiI6ZmFsc2UsImF1dG9idXl0aWVyMDMiOmZhbHNlLCJhdXRvYnV5dGllcjA0IjpmYWxzZSwidXBnZDAxIjoiMCIsInVwZ2QwMiI6IjAiLCJ1cGdkMDMiOiIwIiwidXBnZDA0IjoiMCIsImF1dG9idXl1cGdkMDEiOmZhbHNlLCJhdXRvYnV5dXBnZDAyIjpmYWxzZSwiYXV0b2J1eXVwZ2QwMyI6ZmFsc2UsImF1dG9idXl1cGdkMDQiOmZhbHNlLCJoYXNVbmxvY2tlZFBMMSI6dHJ1ZSwiUEwxZW5lcmd5IjoiMSIsIlBMMXB0cyI6IjAiLCJQTDFwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMMiI6dHJ1ZSwiUEwyZW5lcmd5IjoiMSIsIlBMMnB0cyI6IjAiLCJQTDJwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMMyI6dHJ1ZSwiUEwzZW5lcmd5IjoiMSIsIlBMM3B0cyI6IjAiLCJQTDNwdHN0b3RhbCI6IjAiLCJoYXNVbmxvY2tlZFBMNCI6dHJ1ZSwiUEw0ZW5lcmd5IjoiMSIsIlB MNHB0cyI6IjIiLCJQTDRwdHN0b3RhbCI6IjIiLCJoYXNVbmxvY2tlZFBMNSI6ZmFsc2UsIlB MNWVuZXJneSI6IjEiLCJQTDVwdHMiOiIwIiwiUEw1cHRzdG90YWwiOiIwIiwiaW5jaGEiOjAsImNoYWNvbTAxIjoiMCIsImNoYWNvbTAyIjoiMCIsImNoYWNvbTAzIjoiMCIsImNoYWNvbTA0IjoiMCIsImNoYWNvbTA1IjoiMCIsImNoYWNvbTA2IjoiMCIsImNoYWNvbTA3IjoiMCIsImNoYWNvbTA4IjoiMCIsImNoYWNvbTA5IjoiMCIsImNoYWNvbTEwIjoiMCIsImNoYWNvbTExIjoiMCIsImNoYWNvbTEyIjoiMCIsImNoYWNvbTEzIjoiMCIsImNoYWNvbTE0IjoiMCIsImNoYWNvbTE1IjoiMCIsImNoYWNvbTE2IjoiMCIsImNoYWNvbTE3IjoiMCIsImNoYWNvbTE4IjoiMCIsImNoYWNvbTE5IjoiMCIsImNoYWNvbTIwIjoiMCIsImNoYWNvbTIxIjoiMCIsImNoYWNvbTIyIjoiMCIsImNoYWNvbTIzIjoiMCIsImNoYWNvbTI0IjoiMCIsImhhc1VubG9ja2VkQ2hhIjpmYWxzZSwiYWNoZXZlIjpbXSwiYXV0b0NvbmZpcm0iOmZhbHNlLCJtYXhBbGwiOmZhbHNlLCJ0aW1lIjowLCJsYXN0VGltZSI6MCwidmVyc2lvbiI6IjYuMC4wIn0=',
        author: '6左爷6',
      },
    ]
  },
  {
    name: '扭敧阶段',
    styles: 'background-color: #0000ff; font-size: 24px',
    saves: [
      {
        name: '',
        desc: '',
        data: '',
        author: '',
      },
    ]
  },
  {
    name: '扮敨阶段',
    styles: 'background-color: #ff00ff; font-size: 24px',
    saves: [
      {
        name: '',
        desc: '',
        data: '',
        author: '',
      },
    ]
  },
  {
    name: '扯敩阶段',
    styles: 'background-color: #000000; font-size: 24px',
    saves: [
      {
        name: '',
        desc: '',
        data: '',
        author: '',
      },
    ]
  },
  {
    name: '扰敪阶段',
    styles: 'background-image: linear-gradient(to bottom, #ff0000,#ffff00,#00ff00,#00ffff,#0000ff,#ff00ff,#ff0000); font-size: 24px',
    saves: [
      {
        name: '',
        desc: '',
        data: '',
        author: '',
      },
    ]
  },
  {
    name: '扸敲阶段',
    styles: 'background-color: #888888; color: #000000; font-size: 24px',
    saves: [
      {
        name: '',
        desc: '',
        data: '',
        author: '',
      },
    ]
  },
]
</script>

<style scoped>
.saves {
  width: 90%;
  padding: 7px 25px;
  text-decoration: none;
  border: 1px solid #777;
  background: #333;
  font-family: 'Courier New', sans-serif;
  color: white;
  display: inline-block;
  text-align: center;
}
.category-header {
  cursor: pointer;
}
.category-header:hover {
  opacity: 0.9;
}
.btn {
  cursor: pointer;
  font-size: 12px;
  max-width: 250px;
  padding: 7px 25px;
  text-decoration: none;
  border: 1px solid #777;
  background: #333;
  font-family: 'Courier New', sans-serif;
  color: white;
  display: inline-block;
  margin: 2px;
}
.btn:hover {
  background: #444;
}
</style>
